/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "main.h"

IfxCpu_syncEvent g_cpuSyncEvent = 0;

boolean mode1_status = FALSE;   // button -> checking mode / Use : [Main]
// unsigned short mode1_no = 0;    // checking scenario no / Use : [Main]

boolean mode2_status = FALSE; // button -> parking mode / FALSE : Parking, TRUE : Reverse / Use : [Main]
unsigned short mode2_no = 0;  // parking scenario no / Use : [Main]

unsigned short tuned_distance_state; // tuned distance state // Use : [Sonic, Buzzer, LED, RGB]
unsigned short potentio_value = 0;   // Use : [Potentio, Sonic]

unsigned int time_cnt = 0; // Time Count / 1 second -> Count UP / Use : [Main] 0.01
unsigned int time_cnt_rgb = 0;
unsigned int rgb_en = 1;

unsigned int time_emg = 0;

unsigned int range;
unsigned char range_valid_flag = 0;
unsigned int ranges[10] = {200,};
static boolean btn_check = FALSE;
boolean emg_state = FALSE;

static void InitPATS();
static void FIlterRange(void);

int core0_main(void)
{
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    InitPATS();

    while (1)
    {
    }
    return (1);
}

// Init All
static void InitPATS(void)
{
    InitLED();
    InitRGB();
    InitButton();
    InitTimer();
    InitPotentio();
    InitUltrasonic();
    InitBuzzer();
    initREDLEDPWM();
}

// -------- Button Interrupt  -------- 
__interrupt(0x0B) __vector_table(0) 
void ERU1_ISR(void)
{   
    if(!btn_check) {
        btn_check = TRUE;
        if(!mode1_status && !mode2_status) {
        initREDLEDPWM();
        OpertaionTimer(TRUE, 487);
        mode1_status = TRUE;
        }
        else if(mode1_status && !mode2_status) {
            ResetMode1();
            InitLED();
            OpertaionTimer(TRUE, 487);
            mode2_status = TRUE;
        }
        else {
            ResetMode1();
            ResetMode2();
        }
        btn_check = FALSE;
    }
    
}

/*
// -------- Button 2 Interrupt -------- 
__interrupt(0x0C) __vector_table(0) 
void ERU1_ISR(void)
{
    if(!mode2_status && !mode1_status) {
        OpertaionTimer(TRUE, 487);
        mode2_status = TRUE;
    }
    else {
        ResetMode1();
        ResetMode2();
    }
}
*/

// Ultra Sonic Interrupt
__interrupt(0x0C) __vector_table(0)
void ERU0_ISR(void)
{
    if( (P00_IN.U & (0x1 << P4_BIT_LSB_IDX)) !=0 )        //rising edge of echo
    {   //            ________
        // Echo  _____|
        //
        CCU61_TCTR4.U = (0x1 << T12RS_BIT_LSB_IDX); //Start CCU61 T12 counter
    }
    else        //falling edge of echo
    {
     //   ______
     //  echo   |_______
     //

        CCU61_TCTR4.B.T12RR = 0x1;
        // (1/t_freq)*counter*1000000/58 = centimeter
        range = ((CCU61_T12.B.T12CV)*1000000 / 48828)/58;
        range_valid_flag = 1;
        FIlterRange();
        
        CCU61_TCTR4.B.T12RES = 0x1;
    }
}

//  -------- Timer  -------- 
__interrupt(0x0D) __vector_table(0) 
void CCU60_T12_ISR(void)
{
    P02_OUT.U &= ~(0x1 << P6_BIT_LSB_IDX);
}

//  -------- Timer  -------- 
__interrupt(0x0A) __vector_table(0) 
void CCU60_T13_ISR(void)
{
    // Mode1();
    Mode1_1();
    Mode2();
    time_cnt++;
    time_cnt_rgb++;
    time_emg++;
}

static void FIlterRange(void)
{
    unsigned int sum = range;
    for (char i = 1; i < 10; i++)
    {
        ranges[i-1] = ranges[i];
        sum += ranges[i];
    }
    ranges[9] = range;
    range = sum / 10;
}